[passwords]
Admin = ''
BAKI_1 = 'BAKI_1'
BAKI_2 = 'BAKI_2'
BAKI_3 = 'BAKI_3'
BAKI_4 = 'BAKI_4'
BAKI_5 = 'BAKI_5'
GENCE1 = 'GENCE1'
GENCE2 = 'GENCE2'
GOYCAY = 'GOYCAY'
QUBA = 'QUBA'
LENKERAN = 'LENKERAN'
SABIRABAD = 'SABIRABAD'
SEKI = 'SEKI'